int32 MAX_STRING_LENGTH = 256
int64 camera_id
int32 is_on
int8[256] parent_name
float64 field_of_view
int32[2] resolution
uint64 render_rate
float64[3] camera_pos_b
float64[3] sigma_cb
int8[256] sky_box
int32 post_processing_on
float64 pp_focus_distance
float64 pp_aperture
float64 pp_focal_length
int32 pp_max_blur_size
int32 update_camera_parameters
int32 render_mode
float64[2] depth_map_clipping_planes
