# Structure used to define classic orbit elements

builtin_interfaces/Time stamp
float64 a  # object semi-major axis
float64 e  # Eccentricity of the orbit
float64 i  # inclination of the orbital plane
float64 omega  # Right ascension of the ascending node
float64 f  # True anomaly of the orbit
float64 rmag  # Magnitude of the position vector (extra)
float64 alpha  # Inverted semi-major axis (extra)
float64 rperiap  # Radius of periapsis (extra)
float64 rapoap  # Radius if apoapsis (extra)
