builtin_interfaces/Time stamp
float64 stateofcharge  # [%] Battery state of charge as %-full
float64 stateofchargeah  # [Ah] Battery state of charge un-scaled
float64 solararraytemperature  # [K] Temperature of solar arrays
float64 busvoltage  # [V] Bus voltage
float64 batterycurrent  # [A] Total current flowing through battery
float64 solararraycurrent  # [A] Current sent to battery from solar arrays
float64 batteryemf  # [V] Electro-motive force of battery at this current form look-up table
float64 batteryesr  # [Ohms] Equivalent Series Resistance of battery from look-up table
float64 batteryvoltage  # [V] total voltage across battery
