# Structure used to define the output definition for attitude reference generation

builtin_interfaces/Time stamp
float64[3] r_rn_n  # [m]     spacecraft reference position vector in inertial frame components
float64[3] v_rn_n  # [m/s]  spacecraft reference inertial velocity vector in N frame components
float64[3] a_rn_n  # [m/s^2]    spacecraft reference acceleration vector in N frame components
