# Structure used to test the handling of various built-in types in message payloads across SWIG C/Python bridge

uint8 TYPES_TEST_ARRAY_SIZE = 3

builtin_interfaces/Time stamp
int8 i8test  # Test variable of int8_t
uint8 ui8test  # Test variable of uint8_t
int32 i32test  # Test variable of int32_t
uint32 ui32test  # Test variable of uint32_t
int64 i64test  # Test variable of int64_t
uint64 ui64test  # Test variable of uint64_t
float32 f32test  # Test variable of float
float64 f64test  # Test variable of double
uint8 uint8test  # Test variable of uint8_t (alias)
int8 int8test  # Test variable of int8_t (alias)
bool booltest  # Test variable of bool
int32[3] i32testarray  # Test variable of array of int32_t
uint32[3] ui32testarray  # Test variable of array of uint32_t
int64[3] i64testarray  # Test variable of array of int64_t
uint64[3] ui64testarray  # Test variable of array of uint64_t
uint8[3] uint8testarray  # Array test of uint8_t
int8[3] int8testarray  # Array test of int8_t
bool[3] booltestarray  # Array test of bool
float32[3] f32testarray  # Test variable of array of float
float64[3] f64testarray  # Test variable of array of double
